### PR TITLE
Work around unicode confusion on python2

### PR DESCRIPTION
**Pull request by dwt**
Work around an exception where on centos 7 python 2 will get type confused for filenames containing traditional chinese characters.

I just spent way too much time debugging a weird python 2 edgecase. I know. But at least this seems to work for all python versions I tested this, up to python 3.12.

### CODE REVIEW

**Comment by dwt** [comment]
Ah damn, I just realized you added a changelog file - do you want me to add an entry there?

**Comment by tony** [comment]
@dwt Works for me (at least on Python 3, I don't have easy access to python 2)

Fine if I merge this and make a release on PyPI?

**Comment by tony** [comment]
> Ah damn, I just realized you added a changelog file - do you want me to add an entry there?

Go ahead.

Aside: Any objection to me adding [poetry](https://github.com/python-poetry/poetry) / [ruff](https://github.com/astral-sh/ruff), etc?

**Comment by dwt** [comment]
Ruff: For sure, I use it everywhere nowadays. For poetry, I've not had the best of experiences yet. But this would be a fine project to try it out. So go ahead!

**Comment by dwt** [comment]
How about this?

**Comment by tony** [comment]
@dwt Looks good! Merging!

**Comment by tony** [comment]
@dwt Released [v1.2.2](https://pypi.org/project/watching-testrunner/1.2.2/), any better?

**Pull request merged**
