### PR TITLE
Slightly enhance readme.

### PR DESCRIPTION
**Pull request by dwt**
Hey, I think it's about time you got thanked for the continued work you put into this project.

I also tried to enhance the wording a bit to give a more concise description why this project works the way it works.

What do you think?

### CODE REVIEW

**Review by tony — APPROVED** [review]

**Comment by tony** [comment]
How conscientious of you. Merging.

**Comment by dwt** [comment]
Ha. I might be quite dense. But I just realized that I still have written the readme purely from the perspective of being the project owner. That is actually quite rude of me.

Please feel free to update the readme to reflect that you are the project owner now.

**Comment by tony** [comment]
@dwt Do not worry.

Aside: Do you want it transferred back to you? Do you want to maintain it again? Does that interest you? Or have you moved on? 

If you want, I have enough on my plate projectwise it'd go unnoticed by me if I transferred this back to you.

**Comment by dwt** [comment]
Well to be honest, I quite like being the co-maintainer on this project and not having to cary the torch all by myself. I also love the improvements you have brought to the project, to update it to markdown and all that.

**Comment by tony** [comment]
> Well to be honest, I quite like being the co-maintainer on this project and not having to cary the torch all by myself. I also love the improvements you have brought to the project, to update it to markdown and all that.

Noted 👍.

In regards to co-maintaining: Do you have the permissions you need? Is anything missing? (As this is a personal repo, rather an org repo, there is less flexibility in permissions that can be issued - but I'm open to changing that)

**Comment by dwt** [comment]
I think I have all the permissions I need for now?

Some things I like to add to my projects nowadays is a `Hacking.md` where I outline what I want from pull requests (i.e. unit tests mostly) and how to prepare, test and upload a release. [Example](https://github.com/dwt/fluent/blob/master/Hacking.md).

That would also be an excellent place for us to document how we agree to do this?

For example, do we want all releases go through one of us (you?) would you (also) like to get code reviews from me for changes you do?

In the long run, I kind of miss that this project doesn't have unit-tests, because it's way easier to use `tox` or some such to execute the tests on all supported python versions to verify it still works when fixing bugs like that linux nail biter I found last week. But... it has worked fine so far, so there's no pressing need for me to add them. :/

Stuff like that?

**Comment by tony** [comment]
@dwt I'd like to offer some context in regards to my current situation, and what I would propose if I were to maintan:

1. I don't use watching testrunner anymore. I use [pytest-watcher](https://github.com/olzhasar/pytest-watcher) and [entr](https://github.com/eradman/entr).

    That is why I'm flexible to letting of maintaining this.

2. I have a structure I follow on my projects for CI / linting / testings / packaging / releasing / docs. For instance:
    
    - https://github.com/tmux-python/libtmux, https://libtmux.git-pull.com/
    - https://github.com/vcs-python/libvcs, https://libvcs.git-pull.com/
    
    It changes, none are necessarily best - but since I wrangle a lot of projects, I keep them consistent across the board:
    
    - [poetry](https://github.com/python-poetry/poetry): manages dependencies, virtualenv, and releasing
    - releasing: GitHub actions + https://github.com/pypa/gh-action-pypi-publish
    - format, linting: [ruff](https://github.com/astral-sh/ruff)
    - versions: .tool-versions ([asdf](https://asdf-vm.com/)) and .python-version (to catch [pyenv](https://github.com/pyenv/pyenv)users)
    - sphinx docs w/ [furo](https://github.com/pradyunsg/furo) theme and autodoc
    - no tox, uses GitHub Action Matrix across python versions
    
    If you look at libtmux and libvcs - what do you think of the development setup on those? Any clarifications? Any specific areas where you'd differ or take a different approach? 
    
    If I did continued to maintain: I'd apply my existing dev stack to watching-testrunner and have complete control over how that worked. If I use a linting convention on libvcs, libtmux, any other project of mine, watching-testrunner would, too. It'd be out of expediency as I am scaling across a lot of projects.
    
    If you had big differences on how it'd operate - I'd suggest shifting more of the responsibility on you to maintain and release since they'd be conventions I'm not running in bulk across projects. 

Given the above, how do you feel?

**Comment by dwt** [comment]
If you are not using the tool anymore, I could fully understand shifting the project back to me. Doesn't quite make sense to maintain a project you no longer use. That being said, I still use it very regularly, precisely because tools like `pytest-watcher` and `entr` all default to inotify and similar apis which I've always seen having difficulties in docker / vm setups. (Yes there are workarounds, but if the project is small enough, just use the simpler tool and be done with it).

Regarding point 2, I think your proposed project structure absolutely makes sense and I would love for this project to get that tooling.

**Comment by tony** [comment]
Given the above, since you're around, would you prefer to take any action on these now?

Project ownership:

1. Transfer the project back to you
2. Keep it as-is
3. Revisit later

Tooling:

1. I can adopt the tooling used in my other projects / make a PR to do it.

    Caveat: Python 2 may need to be dropped - I don't think Python 2.x is supported by Poetry, ruff, etc.

2. Keep it as-is
3. You can add any tooling you prefer (now or later)
4. Revisit later

**Comment by dwt** [comment]
If you are not using the project anymore, I would prefer to transfer the project back to me. Especially since I would like to keep the python2 support for some time.

I would love to keep you as a contributor but I understand that you probably will not contribute much if you're not using it anymore.

How do we go about this?

**Pull request merged**
